### ISSUE TITLE
Frequent occurrences of 'app. json: Cannot read properties of undefined (reading' statusText ')`

### ISSUE THREAD

**Issue by FairyWorld** [robisim74/gpt-translate-json#2]
Frequent occurrences of 'app. json: Cannot read properties of undefined (reading' statusText ')`
![image](https://github.com/robisim74/gpt-translate-json/assets/32956212/f9181a41-7bde-4d86-97cb-ce990fe4876e)

**Comment by robisim74** [comment]
@FairyWorld Can you isolate the problem and provide the essential information to recreate the issue?

**Comment by raphaelarias** [comment]
I'm having the same problem, I'm looking into it, but it looks like the problem is on parsing the JSON.

<img width="750" alt="image" src="https://github.com/robisim74/gpt-translate-json/assets/5008166/ccafd8c2-7b04-4704-bc3d-ec1196510006">

We are trying to `JSON.parse` the response, but it doesn't seem to be valid.

<img width="651" alt="image" src="https://github.com/robisim74/gpt-translate-json/assets/5008166/f084aaf9-110d-49ac-a0cd-2537cc3dc6ed">

**Comment by robisim74** [comment]
@raphaelarias Thanks for looking into the issue.

So the array returned by ChatGPT is not a valid json in your case.

Unfortunately I was unable to recreate the problem - a temporary ChatGPT issue? or maybe your starting json is invalid or has some special character?

In any case I released a new version 0.2.0 in which:
- I updated the final request prompt to require a valid json: https://github.com/robisim74/gpt-translate-json/blob/main/src/index.ts#L98
- I updated the openapi library to the latest version
- I improved the error log

Let me know.

**Comment by raphaelarias** [comment]
Thanks for such a fast response @robisim74.

I'm currently assuming that it's due to our JSON being very large? But I think this assumption has flaws.

Our JSON is valid so it seems to be a problem with ChatGPT. In none of our attempts we managed to get it working, so I'm not sure really what was the problem.

I'll check if we have some kinda of a special characters, but it's a valid JSON, so in theory it should still work (?).

I'll try with the new version and revert back soon.

**Comment by raphaelarias** [comment]
For some reason, we are still having the same problem. I'm trying to identify the reason, or find a solution. But for now, I'm not really sure.

<img width="1206" alt="image" src="https://github.com/robisim74/gpt-translate-json/assets/5008166/c56c47ea-7395-4060-82b3-54e808fb5938">

**Comment by robisim74** [comment]
Please could you isolate the file, or part of the file that is creating the problem and post it here?

In the image of the response I see that there are strings with only emoticons... perhaps those could be the problem

**Comment by raphaelarias** [comment]
We have just only one file for the translations. Apparently lowering the tokens even further to 200 seems to fix the issue. At least so far. I'm still trying it out.

**Comment by robisim74** [comment]
gpt-3.5-turbo accept only 16,385 tokens per request. Every request includes the prompt, your original json and the response.

As in docs of this library: `the command splits the files into multiple requests to respect the maximum number of tokens in each request based on the English language, but depending on the target language, the number of tokens used can vary significantly`

If you can confirm that the error is only due to the maximum number of tokens, I can add the suggestion to further reduce the value of the `maxTokens` parameter when this error occurs

**Comment by raphaelarias** [comment]
Sorry, I forgot to reply. It's working as expected. In my opinion, I believe this issue could be closed. I have personally used multiple times, and didn't have this issue anymore.
